name: Churn Prediction CI

on: push


jobs:
    lint:
        run-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup Python
            uses: actions/setup-python@v4

          - name: Install dependencies
            run: |
              python -m pip install 00upgrade pip
              pip install flake8

          - name: Run flake8
            run: |
              flake .