name: Churn Prediction CI

on: push


jobs:
    Statistical_Code_Analysis:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.10.5'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Run flake8 (style Check)
            run: |
              flake8 .

          - name: Run pylint (Code Quality Check)
            run: |
              pylint src/

          - name: Run mypy (Type Checking)
            run: |
              mypy --ignore-missing-imports src/
